### ISSUE TITLE
Callback called multiple times

### ISSUE THREAD

**Issue by axelpale** [rook2pawn/node-filecompare#6]
Async mocha tests require that done() is called only once. Filecompare calls it twice. The following mocha code:

    const filecompare = require('filecompare');

    describe('mymodule', function () {
      it('should call once', function (done) {
        console.log('pre');
          filecompare('index.js', 'LICENSE', function (isEqual) {
            console.log('post');
            return done();
          });
      });
    });

Produces the following output:

        mymodule
    pre
    post
        ✓ should call once

    post
        1) should call once

    1 passing (14ms)
    1 failing

    1) filterxml cli should call once:
       Error: done() called multiple times

Callback should be called only once!

**Comment by rook2pawn** [comment]
Ah thanks for that!  Fixed https://github.com/rook2pawn/node-filecompare/commit/1b529bd9dd9a9079a391d0b9c48e4a4eb2d07d88

**Comment by axelpale** [comment]
This is how we roll. Great!

**Comment by rook2pawn** [comment]
@axelpale check out the new version https://github.com/rook2pawn/node-filecompare/blob/master/lib/index.js when you can. I'm still testing if it can theoretically blow up the call stack with multi gig files. this new one is significantly cleaner.
